import { db, stocksTable } from "@workspace/db";
import { sql } from "drizzle-orm";

const SEED_STOCKS = [
  {
    "ticker": "AAPL",
    "name": "Apple Inc.",
    "sector": "Technology",
    "price": 227.48,
    "peRatio": 37.5,
    "debtToEquity": 1.87,
    "epsGrowth": 10.2,
    "dividendYield": 0.44,
    "roe": 157.4,
    "revenueGrowth": 5,
    "profitMargin": 26.3,
    "currentRatio": 0.87,
    "marketCapB": 3440,
    "beta": 1.24
  },
  {
    "ticker": "ABBV",
    "name": "AbbVie Inc.",
    "sector": "Healthcare",
    "price": 174.3,
    "peRatio": 16.2,
    "debtToEquity": 6.2,
    "epsGrowth": 2,
    "dividendYield": 3.45,
    "roe": 999,
    "revenueGrowth": 3.7,
    "profitMargin": 18.3,
    "currentRatio": 0.55,
    "marketCapB": 308,
    "beta": 0.65
  },
  {
    "ticker": "ACN",
    "name": "Accenture plc",
    "sector": "Technology",
    "price": 332.1,
    "peRatio": 29.3,
    "debtToEquity": 0.08,
    "epsGrowth": 5,
    "dividendYield": 1.72,
    "roe": 32.1,
    "revenueGrowth": 1,
    "profitMargin": 10.9,
    "currentRatio": 1.38,
    "marketCapB": 210,
    "beta": 1.1
  },
  {
    "ticker": "ADBE",
    "name": "Adobe Inc.",
    "sector": "Technology",
    "price": 460.2,
    "peRatio": 29.1,
    "debtToEquity": 0.43,
    "epsGrowth": 15,
    "dividendYield": 0,
    "roe": 33.5,
    "revenueGrowth": 10,
    "profitMargin": 26,
    "currentRatio": 1.07,
    "marketCapB": 203,
    "beta": 1.39
  },
  {
    "ticker": "AMD",
    "name": "Advanced Micro Devices",
    "sector": "Technology",
    "price": 157.4,
    "peRatio": 115,
    "debtToEquity": 0.05,
    "epsGrowth": -58,
    "dividendYield": 0,
    "roe": 2.5,
    "revenueGrowth": 16,
    "profitMargin": 5.9,
    "currentRatio": 2.58,
    "marketCapB": 256,
    "beta": 1.72
  },
  {
    "ticker": "AMGN",
    "name": "Amgen Inc.",
    "sector": "Healthcare",
    "price": 317.2,
    "peRatio": 15.7,
    "debtToEquity": 8.1,
    "epsGrowth": 26,
    "dividendYield": 3.4,
    "roe": 76.4,
    "revenueGrowth": 19,
    "profitMargin": 29.3,
    "currentRatio": 1.3,
    "marketCapB": 170,
    "beta": 0.41
  },
  {
    "ticker": "AMZN",
    "name": "Amazon.com Inc.",
    "sector": "Consumer",
    "price": 198.3,
    "peRatio": 42.5,
    "debtToEquity": 0.54,
    "epsGrowth": 95,
    "dividendYield": 0,
    "roe": 23.8,
    "revenueGrowth": 12.5,
    "profitMargin": 8,
    "currentRatio": 1.06,
    "marketCapB": 2070,
    "beta": 1.15
  },
  {
    "ticker": "AVGO",
    "name": "Broadcom Inc.",
    "sector": "Technology",
    "price": 167.5,
    "peRatio": 32.8,
    "debtToEquity": 1.52,
    "epsGrowth": 47,
    "dividendYield": 1.37,
    "roe": 43.1,
    "revenueGrowth": 51,
    "profitMargin": 37.1,
    "currentRatio": 1.03,
    "marketCapB": 787,
    "beta": 1.08
  },
  {
    "ticker": "AXP",
    "name": "American Express Co.",
    "sector": "Financial",
    "price": 281,
    "peRatio": 19.4,
    "debtToEquity": 1.73,
    "epsGrowth": 23,
    "dividendYield": 1.12,
    "roe": 34.1,
    "revenueGrowth": 9,
    "profitMargin": 16.1,
    "currentRatio": 1.41,
    "marketCapB": 201,
    "beta": 1.11
  },
  {
    "ticker": "BAC",
    "name": "Bank of America Corp.",
    "sector": "Financial",
    "price": 40.5,
    "peRatio": 13.8,
    "debtToEquity": 1.14,
    "epsGrowth": 8,
    "dividendYield": 2.27,
    "roe": 9.5,
    "revenueGrowth": 5,
    "profitMargin": 23.2,
    "currentRatio": 0.73,
    "marketCapB": 322,
    "beta": 1.35
  },
  {
    "ticker": "BRK.B",
    "name": "Berkshire Hathaway Inc.",
    "sector": "Financial",
    "price": 457.2,
    "peRatio": 10.2,
    "debtToEquity": 0.27,
    "epsGrowth": 21,
    "dividendYield": 0,
    "roe": 14.3,
    "revenueGrowth": 5,
    "profitMargin": 15.2,
    "currentRatio": 1.82,
    "marketCapB": 996,
    "beta": 0.88
  },
  {
    "ticker": "CAT",
    "name": "Caterpillar Inc.",
    "sector": "Industrial",
    "price": 364.5,
    "peRatio": 17.5,
    "debtToEquity": 1.75,
    "epsGrowth": -8,
    "dividendYield": 1.63,
    "roe": 58.4,
    "revenueGrowth": -3,
    "profitMargin": 17.8,
    "currentRatio": 1.24,
    "marketCapB": 179,
    "beta": 1.03
  },
  {
    "ticker": "COST",
    "name": "Costco Wholesale Corp.",
    "sector": "Consumer",
    "price": 907.4,
    "peRatio": 52.5,
    "debtToEquity": 0.36,
    "epsGrowth": 17,
    "dividendYield": 0.57,
    "roe": 33.5,
    "revenueGrowth": 8,
    "profitMargin": 2.9,
    "currentRatio": 0.96,
    "marketCapB": 402,
    "beta": 0.75
  },
  {
    "ticker": "CRM",
    "name": "Salesforce Inc.",
    "sector": "Technology",
    "price": 294.8,
    "peRatio": 33.4,
    "debtToEquity": 0.15,
    "epsGrowth": 43,
    "dividendYield": 0,
    "roe": 10.1,
    "revenueGrowth": 9,
    "profitMargin": 15.8,
    "currentRatio": 1.06,
    "marketCapB": 284,
    "beta": 1.3
  },
  {
    "ticker": "CVX",
    "name": "Chevron Corp.",
    "sector": "Energy",
    "price": 143.7,
    "peRatio": 13.9,
    "debtToEquity": 0.17,
    "epsGrowth": -18,
    "dividendYield": 4.37,
    "roe": 10.8,
    "revenueGrowth": -8,
    "profitMargin": 8.5,
    "currentRatio": 1.37,
    "marketCapB": 265,
    "beta": 1.03
  },
  {
    "ticker": "GE",
    "name": "GE Aerospace",
    "sector": "Industrial",
    "price": 166.7,
    "peRatio": 31.5,
    "debtToEquity": 0.86,
    "epsGrowth": 143,
    "dividendYield": 0.71,
    "roe": 27.9,
    "revenueGrowth": 6,
    "profitMargin": 16.4,
    "currentRatio": 1.38,
    "marketCapB": 181,
    "beta": 1.07
  },
  {
    "ticker": "GOOGL",
    "name": "Alphabet Inc.",
    "sector": "Technology",
    "price": 174.5,
    "peRatio": 23.1,
    "debtToEquity": 0.05,
    "epsGrowth": 36.8,
    "dividendYield": 0.46,
    "roe": 32,
    "revenueGrowth": 14,
    "profitMargin": 29.5,
    "currentRatio": 2.1,
    "marketCapB": 2140,
    "beta": 1.06
  },
  {
    "ticker": "GS",
    "name": "Goldman Sachs Group",
    "sector": "Financial",
    "price": 519.3,
    "peRatio": 14.3,
    "debtToEquity": 5.42,
    "epsGrowth": 92,
    "dividendYield": 2.33,
    "roe": 12.7,
    "revenueGrowth": 13,
    "profitMargin": 23.5,
    "currentRatio": 1.02,
    "marketCapB": 177,
    "beta": 1.32
  },
  {
    "ticker": "HD",
    "name": "The Home Depot Inc.",
    "sector": "Consumer",
    "price": 389.5,
    "peRatio": 25.8,
    "debtToEquity": 999,
    "epsGrowth": -3,
    "dividendYield": 2.39,
    "roe": 999,
    "revenueGrowth": -3,
    "profitMargin": 10.2,
    "currentRatio": 1.35,
    "marketCapB": 386,
    "beta": 1.04
  },
  {
    "ticker": "HON",
    "name": "Honeywell International",
    "sector": "Industrial",
    "price": 216.4,
    "peRatio": 22.5,
    "debtToEquity": 0.9,
    "epsGrowth": 8,
    "dividendYield": 2.2,
    "roe": 33.5,
    "revenueGrowth": 4,
    "profitMargin": 15.7,
    "currentRatio": 1.14,
    "marketCapB": 136,
    "beta": 0.84
  },
  {
    "ticker": "IBM",
    "name": "IBM Corp.",
    "sector": "Technology",
    "price": 215.5,
    "peRatio": 28.3,
    "debtToEquity": 3.2,
    "epsGrowth": -17,
    "dividendYield": 3.1,
    "roe": 26.4,
    "revenueGrowth": 3,
    "profitMargin": 12.2,
    "currentRatio": 0.95,
    "marketCapB": 199,
    "beta": 0.62
  },
  {
    "ticker": "INTC",
    "name": "Intel Corp.",
    "sector": "Technology",
    "price": 22.3,
    "peRatio": 99,
    "debtToEquity": 0.52,
    "epsGrowth": -100,
    "dividendYield": 0,
    "roe": -12.3,
    "revenueGrowth": -9,
    "profitMargin": -14.9,
    "currentRatio": 1.39,
    "marketCapB": 94,
    "beta": 0.72
  },
  {
    "ticker": "INTU",
    "name": "Intuit Inc.",
    "sector": "Technology",
    "price": 617.5,
    "peRatio": 52,
    "debtToEquity": 0.64,
    "epsGrowth": 14,
    "dividendYield": 0.6,
    "roe": 18.1,
    "revenueGrowth": 15,
    "profitMargin": 18.5,
    "currentRatio": 1.18,
    "marketCapB": 173,
    "beta": 1.26
  },
  {
    "ticker": "JNJ",
    "name": "Johnson & Johnson",
    "sector": "Healthcare",
    "price": 159.8,
    "peRatio": 15.8,
    "debtToEquity": 0.48,
    "epsGrowth": 10,
    "dividendYield": 3.21,
    "roe": 24.2,
    "revenueGrowth": 6,
    "profitMargin": 11,
    "currentRatio": 1.07,
    "marketCapB": 384,
    "beta": 0.56
  },
  {
    "ticker": "JPM",
    "name": "JPMorgan Chase & Co.",
    "sector": "Financial",
    "price": 215.3,
    "peRatio": 11.5,
    "debtToEquity": 1.24,
    "epsGrowth": 17,
    "dividendYield": 2.22,
    "roe": 17.5,
    "revenueGrowth": 18,
    "profitMargin": 31.5,
    "currentRatio": 0.92,
    "marketCapB": 623,
    "beta": 1.08
  },
  {
    "ticker": "KO",
    "name": "The Coca-Cola Co.",
    "sector": "Consumer",
    "price": 64.8,
    "peRatio": 24.5,
    "debtToEquity": 1.82,
    "epsGrowth": 6,
    "dividendYield": 3.08,
    "roe": 40.7,
    "revenueGrowth": 3,
    "profitMargin": 22.8,
    "currentRatio": 1.05,
    "marketCapB": 279,
    "beta": 0.59
  },
  {
    "ticker": "LLY",
    "name": "Eli Lilly and Co.",
    "sector": "Healthcare",
    "price": 785.4,
    "peRatio": 81.5,
    "debtToEquity": 1.85,
    "epsGrowth": 148,
    "dividendYield": 0.69,
    "roe": 63.8,
    "revenueGrowth": 36,
    "profitMargin": 21.7,
    "currentRatio": 1.16,
    "marketCapB": 748,
    "beta": 0.51
  },
  {
    "ticker": "LOW",
    "name": "Lowe's Companies Inc.",
    "sector": "Consumer",
    "price": 233.8,
    "peRatio": 21,
    "debtToEquity": 999,
    "epsGrowth": 7,
    "dividendYield": 1.9,
    "roe": 999,
    "revenueGrowth": -4,
    "profitMargin": 10.2,
    "currentRatio": 1.16,
    "marketCapB": 136,
    "beta": 1.09
  },
  {
    "ticker": "MA",
    "name": "Mastercard Inc.",
    "sector": "Financial",
    "price": 501.8,
    "peRatio": 38.5,
    "debtToEquity": 2.08,
    "epsGrowth": 21,
    "dividendYield": 0.54,
    "roe": 212.6,
    "revenueGrowth": 11,
    "profitMargin": 45.9,
    "currentRatio": 1.16,
    "marketCapB": 465,
    "beta": 1.1
  },
  {
    "ticker": "MCD",
    "name": "McDonald's Corp.",
    "sector": "Consumer",
    "price": 294.7,
    "peRatio": 24.5,
    "debtToEquity": 999,
    "epsGrowth": 2,
    "dividendYield": 2.33,
    "roe": 999,
    "revenueGrowth": 1.5,
    "profitMargin": 33.2,
    "currentRatio": 1.28,
    "marketCapB": 217,
    "beta": 0.76
  },
  {
    "ticker": "META",
    "name": "Meta Platforms Inc.",
    "sector": "Technology",
    "price": 563.8,
    "peRatio": 26.5,
    "debtToEquity": 0.06,
    "epsGrowth": 73,
    "dividendYield": 0.35,
    "roe": 36.6,
    "revenueGrowth": 22,
    "profitMargin": 38,
    "currentRatio": 2.69,
    "marketCapB": 1430,
    "beta": 1.22
  },
  {
    "ticker": "MSFT",
    "name": "Microsoft Corp.",
    "sector": "Technology",
    "price": 415.2,
    "peRatio": 35.8,
    "debtToEquity": 0.29,
    "epsGrowth": 21.5,
    "dividendYield": 0.72,
    "roe": 35.6,
    "revenueGrowth": 16,
    "profitMargin": 35.6,
    "currentRatio": 1.27,
    "marketCapB": 3090,
    "beta": 0.9
  },
  {
    "ticker": "NEE",
    "name": "NextEra Energy Inc.",
    "sector": "Utilities",
    "price": 72.8,
    "peRatio": 22.8,
    "debtToEquity": 1.29,
    "epsGrowth": 39,
    "dividendYield": 2.81,
    "roe": 13.5,
    "revenueGrowth": -5,
    "profitMargin": 23.4,
    "currentRatio": 0.42,
    "marketCapB": 148,
    "beta": 0.51
  },
  {
    "ticker": "NFLX",
    "name": "Netflix Inc.",
    "sector": "Technology",
    "price": 701,
    "peRatio": 49.5,
    "debtToEquity": 0.82,
    "epsGrowth": 102,
    "dividendYield": 0,
    "roe": 38.8,
    "revenueGrowth": 15,
    "profitMargin": 22.5,
    "currentRatio": 1.25,
    "marketCapB": 303,
    "beta": 1.43
  },
  {
    "ticker": "NVDA",
    "name": "NVIDIA Corp.",
    "sector": "Technology",
    "price": 134.5,
    "peRatio": 64.2,
    "debtToEquity": 0.17,
    "epsGrowth": 168,
    "dividendYield": 0.03,
    "roe": 115.8,
    "revenueGrowth": 122,
    "profitMargin": 55.8,
    "currentRatio": 4.17,
    "marketCapB": 3290,
    "beta": 1.67
  },
  {
    "ticker": "ORCL",
    "name": "Oracle Corp.",
    "sector": "Technology",
    "price": 163.4,
    "peRatio": 31.2,
    "debtToEquity": 999,
    "epsGrowth": 18,
    "dividendYield": 0.98,
    "roe": 999,
    "revenueGrowth": 6,
    "profitMargin": 24.7,
    "currentRatio": 0.87,
    "marketCapB": 451,
    "beta": 0.95
  },
  {
    "ticker": "PEP",
    "name": "PepsiCo Inc.",
    "sector": "Consumer",
    "price": 165.4,
    "peRatio": 22.3,
    "debtToEquity": 2.6,
    "epsGrowth": -0.5,
    "dividendYield": 3.32,
    "roe": 53.4,
    "revenueGrowth": 0.6,
    "profitMargin": 10.9,
    "currentRatio": 0.79,
    "marketCapB": 228,
    "beta": 0.61
  },
  {
    "ticker": "PFE",
    "name": "Pfizer Inc.",
    "sector": "Healthcare",
    "price": 29.3,
    "peRatio": 99,
    "debtToEquity": 0.64,
    "epsGrowth": -66,
    "dividendYield": 6.64,
    "roe": 1.7,
    "revenueGrowth": -41,
    "profitMargin": 1.6,
    "currentRatio": 1.28,
    "marketCapB": 166,
    "beta": 0.44
  },
  {
    "ticker": "PG",
    "name": "Procter & Gamble Co.",
    "sector": "Consumer",
    "price": 161.2,
    "peRatio": 28.3,
    "debtToEquity": 0.67,
    "epsGrowth": 12,
    "dividendYield": 2.34,
    "roe": 32.4,
    "revenueGrowth": 3,
    "profitMargin": 18.6,
    "currentRatio": 0.73,
    "marketCapB": 381,
    "beta": 0.55
  },
  {
    "ticker": "RTX",
    "name": "RTX Corp.",
    "sector": "Industrial",
    "price": 120.1,
    "peRatio": 35.2,
    "debtToEquity": 0.85,
    "epsGrowth": 20,
    "dividendYield": 2.03,
    "roe": 9.9,
    "revenueGrowth": 13,
    "profitMargin": 5.1,
    "currentRatio": 1.1,
    "marketCapB": 158,
    "beta": 0.66
  },
  {
    "ticker": "SPGI",
    "name": "S&P Global Inc.",
    "sector": "Financial",
    "price": 491.7,
    "peRatio": 48,
    "debtToEquity": 0.8,
    "epsGrowth": 25,
    "dividendYield": 0.78,
    "roe": 24.5,
    "revenueGrowth": 12,
    "profitMargin": 26.8,
    "currentRatio": 1.32,
    "marketCapB": 158,
    "beta": 0.94
  },
  {
    "ticker": "T",
    "name": "AT&T Inc.",
    "sector": "Telecom",
    "price": 22.3,
    "peRatio": 12.5,
    "debtToEquity": 1.17,
    "epsGrowth": -19,
    "dividendYield": 5.73,
    "roe": 12.1,
    "revenueGrowth": 0.7,
    "profitMargin": 10.4,
    "currentRatio": 0.65,
    "marketCapB": 160,
    "beta": 0.66
  },
  {
    "ticker": "TMO",
    "name": "Thermo Fisher Scientific",
    "sector": "Healthcare",
    "price": 489.1,
    "peRatio": 27.8,
    "debtToEquity": 0.7,
    "epsGrowth": -14,
    "dividendYield": 0.33,
    "roe": 14,
    "revenueGrowth": -4,
    "profitMargin": 12.2,
    "currentRatio": 2.02,
    "marketCapB": 188,
    "beta": 0.78
  },
  {
    "ticker": "TSLA",
    "name": "Tesla Inc.",
    "sector": "Consumer",
    "price": 248.5,
    "peRatio": 78.3,
    "debtToEquity": 0.07,
    "epsGrowth": -71,
    "dividendYield": 0,
    "roe": 10,
    "revenueGrowth": 1,
    "profitMargin": 5.5,
    "currentRatio": 1.84,
    "marketCapB": 793,
    "beta": 2.31
  },
  {
    "ticker": "UNH",
    "name": "UnitedHealth Group Inc.",
    "sector": "Healthcare",
    "price": 487.8,
    "peRatio": 22.1,
    "debtToEquity": 0.73,
    "epsGrowth": -3,
    "dividendYield": 1.43,
    "roe": 25.5,
    "revenueGrowth": 8,
    "profitMargin": 5.9,
    "currentRatio": 0.77,
    "marketCapB": 447,
    "beta": 0.57
  },
  {
    "ticker": "V",
    "name": "Visa Inc.",
    "sector": "Financial",
    "price": 295.4,
    "peRatio": 33.8,
    "debtToEquity": 0.62,
    "epsGrowth": 17,
    "dividendYield": 0.73,
    "roe": 52.5,
    "revenueGrowth": 10,
    "profitMargin": 54.5,
    "currentRatio": 1.44,
    "marketCapB": 629,
    "beta": 0.93
  },
  {
    "ticker": "VZ",
    "name": "Verizon Communications",
    "sector": "Telecom",
    "price": 40.7,
    "peRatio": 10.3,
    "debtToEquity": 1.66,
    "epsGrowth": -5,
    "dividendYield": 6.41,
    "roe": 21.3,
    "revenueGrowth": 0.9,
    "profitMargin": 15.6,
    "currentRatio": 0.71,
    "marketCapB": 172,
    "beta": 0.38
  },
  {
    "ticker": "WMT",
    "name": "Walmart Inc.",
    "sector": "Consumer",
    "price": 91.3,
    "peRatio": 37,
    "debtToEquity": 0.68,
    "epsGrowth": 140,
    "dividendYield": 1.01,
    "roe": 22.2,
    "revenueGrowth": 5,
    "profitMargin": 2.4,
    "currentRatio": 0.83,
    "marketCapB": 735,
    "beta": 0.56
  },
  {
    "ticker": "XOM",
    "name": "Exxon Mobil Corp.",
    "sector": "Energy",
    "price": 113.4,
    "peRatio": 14.6,
    "debtToEquity": 0.19,
    "epsGrowth": -13,
    "dividendYield": 3.37,
    "roe": 14,
    "revenueGrowth": 1.4,
    "profitMargin": 8.9,
    "currentRatio": 1.44,
    "marketCapB": 454,
    "beta": 0.93
  },
  { ticker: "CSCO", name: "Cisco Systems Inc.", sector: "Technology", price: 59.2, peRatio: 17.1, debtToEquity: 0.23, epsGrowth: 6, dividendYield: 2.91, roe: 33.8, revenueGrowth: 1, profitMargin: 21.8, currentRatio: 1.57, marketCapB: 239, beta: 0.83 },
  { ticker: "DIS", name: "Walt Disney Co.", sector: "Consumer", price: 111.4, peRatio: 42.2, debtToEquity: 0.47, epsGrowth: 78, dividendYield: 0, roe: 5.7, revenueGrowth: 4, profitMargin: 4.3, currentRatio: 1.22, marketCapB: 203, beta: 1.21 },
  { ticker: "WFC", name: "Wells Fargo & Co.", sector: "Financial", price: 70.8, peRatio: 13.2, debtToEquity: 1.09, epsGrowth: 28, dividendYield: 2.05, roe: 12.1, revenueGrowth: 10, profitMargin: 24.8, currentRatio: 0.88, marketCapB: 241, beta: 1.14 },
  { ticker: "MRK", name: "Merck & Co. Inc.", sector: "Healthcare", price: 91.3, peRatio: 14.1, debtToEquity: 0.72, epsGrowth: -1, dividendYield: 3.47, roe: 37.2, revenueGrowth: 7, profitMargin: 21.3, currentRatio: 1.22, marketCapB: 231, beta: 0.39 },
  { ticker: "TXN", name: "Texas Instruments Inc.", sector: "Technology", price: 171.5, peRatio: 31.4, debtToEquity: 1.08, epsGrowth: -33, dividendYield: 2.96, roe: 44.7, revenueGrowth: -11, profitMargin: 33.5, currentRatio: 3.69, marketCapB: 156, beta: 1.01 },
  { ticker: "NOW", name: "ServiceNow Inc.", sector: "Technology", price: 871.2, peRatio: 89.5, debtToEquity: 0.17, epsGrowth: 64, dividendYield: 0, roe: 15.1, revenueGrowth: 22, profitMargin: 14.3, currentRatio: 1.09, marketCapB: 179, beta: 1.12 },
  { ticker: "NKE", name: "Nike Inc.", sector: "Consumer", price: 75.6, peRatio: 21.8, debtToEquity: 1.86, epsGrowth: -26, dividendYield: 2.19, roe: 26.4, revenueGrowth: -10, profitMargin: 9.4, currentRatio: 2.52, marketCapB: 113, beta: 0.96 },
  { ticker: "MS", name: "Morgan Stanley", sector: "Financial", price: 114.3, peRatio: 17.8, debtToEquity: 3.52, epsGrowth: 24, dividendYield: 3.15, roe: 13.7, revenueGrowth: 14, profitMargin: 17.4, currentRatio: 0.81, marketCapB: 193, beta: 1.31 },
  { ticker: "C", name: "Citigroup Inc.", sector: "Financial", price: 70.1, peRatio: 12.9, debtToEquity: 1.48, epsGrowth: 37, dividendYield: 3.11, roe: 7.2, revenueGrowth: 4, profitMargin: 13.5, currentRatio: 0.78, marketCapB: 135, beta: 1.41 },
  { ticker: "MDT", name: "Medtronic plc", sector: "Healthcare", price: 88.7, peRatio: 16.3, debtToEquity: 0.51, epsGrowth: -6, dividendYield: 3.41, roe: 8.8, revenueGrowth: 3, profitMargin: 13.9, currentRatio: 2.19, marketCapB: 116, beta: 0.62 },
  { ticker: "DHR", name: "Danaher Corp.", sector: "Healthcare", price: 230.1, peRatio: 32.5, debtToEquity: 0.28, epsGrowth: -37, dividendYield: 0.41, roe: 8.9, revenueGrowth: -6, profitMargin: 18.1, currentRatio: 1.62, marketCapB: 165, beta: 0.73 },
  { ticker: "QCOM", name: "Qualcomm Inc.", sector: "Technology", price: 153.8, peRatio: 17.4, debtToEquity: 1.66, epsGrowth: 33, dividendYield: 2.08, roe: 42.3, revenueGrowth: 9, profitMargin: 26.7, currentRatio: 2.67, marketCapB: 172, beta: 1.32 },
  { ticker: "TGT", name: "Target Corp.", sector: "Consumer", price: 130.4, peRatio: 13.5, debtToEquity: 2.37, epsGrowth: -18, dividendYield: 3.54, roe: 29.3, revenueGrowth: -4, profitMargin: 4.2, currentRatio: 0.91, marketCapB: 60, beta: 0.72 },
  { ticker: "UPS", name: "United Parcel Service", sector: "Industrial", price: 105.3, peRatio: 16.1, debtToEquity: 1.52, epsGrowth: -23, dividendYield: 6.07, roe: 47.2, revenueGrowth: -9, profitMargin: 7.5, currentRatio: 1.17, marketCapB: 90, beta: 0.96 },
  { ticker: "PANW", name: "Palo Alto Networks", sector: "Technology", price: 172.6, peRatio: 48.2, debtToEquity: 0.32, epsGrowth: 411, dividendYield: 0, roe: 12.6, revenueGrowth: 16, profitMargin: 9.3, currentRatio: 0.82, marketCapB: 112, beta: 1.07 },
  { ticker: "SO", name: "Southern Company", sector: "Utilities", price: 87.1, peRatio: 22.4, debtToEquity: 1.68, epsGrowth: 42, dividendYield: 3.27, roe: 13.5, revenueGrowth: 6, profitMargin: 15.2, currentRatio: 0.77, marketCapB: 96, beta: 0.41 },
  { ticker: "DUK", name: "Duke Energy Corp.", sector: "Utilities", price: 109.5, peRatio: 19.8, debtToEquity: 1.91, epsGrowth: 3, dividendYield: 3.68, roe: 9.1, revenueGrowth: 5, profitMargin: 13.8, currentRatio: 0.59, marketCapB: 84, beta: 0.43 },
  { ticker: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare", price: 56.8, peRatio: 17.3, debtToEquity: 2.14, epsGrowth: -91, dividendYield: 4.58, roe: 7.8, revenueGrowth: 7, profitMargin: 5.2, currentRatio: 1.25, marketCapB: 113, beta: 0.34 },
  { ticker: "GILD", name: "Gilead Sciences Inc.", sector: "Healthcare", price: 110.2, peRatio: 21.5, debtToEquity: 1.31, epsGrowth: 48, dividendYield: 3.12, roe: 28.4, revenueGrowth: 6, profitMargin: 23.1, currentRatio: 1.59, marketCapB: 137, beta: 0.31 },
  { ticker: "ETN", name: "Eaton Corp. plc", sector: "Industrial", price: 291.4, peRatio: 29.7, debtToEquity: 0.38, epsGrowth: 20, dividendYield: 1.37, roe: 20.3, revenueGrowth: 8, profitMargin: 16.5, currentRatio: 1.31, marketCapB: 116, beta: 1.08 },
  { ticker: "ITW", name: "Illinois Tool Works", sector: "Industrial", price: 254.7, peRatio: 23.1, debtToEquity: 999, epsGrowth: -2, dividendYield: 2.43, roe: 999, revenueGrowth: -1, profitMargin: 22.9, currentRatio: 1.36, marketCapB: 79, beta: 1.05 },
  { ticker: "F", name: "Ford Motor Co.", sector: "Consumer", price: 10.2, peRatio: 12.3, debtToEquity: 3.44, epsGrowth: -82, dividendYield: 6.69, roe: 5.1, revenueGrowth: 5, profitMargin: 1.6, currentRatio: 1.16, marketCapB: 41, beta: 1.53 },
  { ticker: "GM", name: "General Motors Co.", sector: "Consumer", price: 49.1, peRatio: 5.9, debtToEquity: 1.89, epsGrowth: 26, dividendYield: 1.05, roe: 16.5, revenueGrowth: 9, profitMargin: 5.2, currentRatio: 1.07, marketCapB: 54, beta: 1.33 },
  { ticker: "SLB", name: "SLB (Schlumberger)", sector: "Energy", price: 41.3, peRatio: 14.2, debtToEquity: 0.54, epsGrowth: 14, dividendYield: 2.91, roe: 21.9, revenueGrowth: 10, profitMargin: 11.5, currentRatio: 1.31, marketCapB: 59, beta: 1.24 },
  { ticker: "MO", name: "Altria Group Inc.", sector: "Consumer", price: 54.7, peRatio: 10.2, debtToEquity: 999, epsGrowth: 5, dividendYield: 7.34, roe: 999, revenueGrowth: 1, profitMargin: 46.7, currentRatio: 0.42, marketCapB: 93, beta: 0.55 },
  { ticker: "ISRG", name: "Intuitive Surgical Inc.", sector: "Healthcare", price: 494.3, peRatio: 72.4, debtToEquity: 0.0, epsGrowth: 25, dividendYield: 0, roe: 15.3, revenueGrowth: 16, profitMargin: 22.1, currentRatio: 4.37, marketCapB: 176, beta: 1.07 },
  { ticker: "PYPL", name: "PayPal Holdings Inc.", sector: "Financial", price: 76.4, peRatio: 17.8, debtToEquity: 0.59, epsGrowth: 20, dividendYield: 0, roe: 19.5, revenueGrowth: 7, profitMargin: 15.2, currentRatio: 1.28, marketCapB: 77, beta: 1.52 },
  { ticker: "USB", name: "U.S. Bancorp", sector: "Financial", price: 42.7, peRatio: 12.8, debtToEquity: 1.22, epsGrowth: 4, dividendYield: 4.18, roe: 11.8, revenueGrowth: 2, profitMargin: 18.5, currentRatio: 0.72, marketCapB: 66, beta: 0.98 }
] as const;

export async function seedStocksIfEmpty() {
  console.log("[seed] Checking for new stocks to add...");
  await db.insert(stocksTable).values(
    SEED_STOCKS.map(s => ({ ...s, updatedAt: new Date() }))
  ).onConflictDoNothing();
  console.log("[seed] Stock seed complete.");
}
